---
# tasks file for Ansible_Cisco_ios_12.2_hardening_w-NAPALM

  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"
       
# Backup config. Make sure to not run backup again in playbook
# later runs overwrite this backup.
  - name: Backup current config
    ios_config:
      backup: yes
      provider: "{{ provider }}"
    register: backup_config

  - debug:
      var: backup_config.backup_path
      verbosity: 3


  - name: "create a diff"
    napalm_install_config:
      hostname: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      dev_os: "ios"
      config_file: ./vars/initial.conf
      commit_changes: true
      replace_config: true
      diff_file: ./vars/initial.diff

