---
# tasks file for Ansible_Cisco_ios_12.2_hardening_w-NAPALM

  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"
        transport: cli


  - name: "create a diff"
    napalm_install_config:
      hostname: "{{ inventory_hostname }}"
      username: "{{ creds['username'] }}"
      password: "{{ creds['password'] }}"
      dev_os: "ios"
      config_file: ./vars/initial.conf
      commit_changes: false
      replace_config: false
      diff_file: ./vars/initial.diff

